from user.views.user_signup_view import UserSignUpView
from user.views.user_login_view import UserLoginView
from user.views.get_user_view import UserList
from user.views.nearby_barber_view import NearbyBarber
from user.views.nearby_chef_view import NearbyChef
from user.views.nearby_driver_view import NearbyDriver
from user.views.nearby_baby_sitter_view import NearbyBabysitter
from user.views.nearby_pet_trainer_view import NearbyPetTrainer
from user.views.chef_reservation_view import ChefReservation
from user.views.diver_reservation_view import DriverReservation
from user.views.barber_reservation_view import BarberReservation
from user.views.baby_sitter_reservation_view import BabySitterReservation
from user.views.pet_trainer_reservation_view import PetTrainerReservation