from service.views.add_chef_view import AddChefView
from service.views.add_driver_view import AddDriverView
from service.views.add_barber_view import AddBarberView
from service.views.add_pet_trainer_view import AddPetTrainer
from service.views.add_baby_sitter_view import AddBabySitterView
from service.views.update_chef_view import UpdateChef
from service.views.update_driver_view import UpdateDriver
from service.views.update_barber_view import UpdateBarber
from service.views.update_baby_sitter_view import UpdateBabySitter
from service.views.update_pet_trainer_view import UpdatePetTrainer